nodeLinker: node-modules

defaultSemverRangePrefix: ""

# enableGlobalCache: false

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - x64
    - wasm32
    - arm64
  # libc:
  #   - musl

yarnPath: .yarn/releases/yarn-4.1.1.cjs
